package TrelloTests;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

public class TrelloBoards extends TestBase {

    @BeforeMethod
    public void initTests() {
        //Clicking login button
        driver.findElement(By.xpath("//a[@class='btn btn-sm btn-link text-white']")).click();
        waitUntilElementIsClickable(By.id("login"), 10);
        //Entering credentials and logging in
        driver.findElement(By.xpath("//input[@id='user']")).sendKeys(LOGIN);
        driver.findElement(By.xpath("//input[@id='password']")).sendKeys(PASSWORD);
        waitUntilElementIsClickable(By.id("login"), 10);
        driver.findElement(By.cssSelector("#login")).click();
        waitUntilElementIsVisible((By.className("home-sticky-container")), 20);
        //Entering the workspace
        driver.get(WORKSPACE_NAME);
        waitUntilElementIsVisible((By.xpath(boardLocator(BOARD_TITLE))), 20);
        //Entering our board
        WebElement ourBoard = driver.findElement(By.xpath(boardLocator(BOARD_TITLE)));
        ourBoard.click();
        waitUntilElementIsVisible((By.id("board")), 20);

    }

    @Test
    public void trelloAddNewList() {
        //Checking quantity of lists
        System.out.println("Quantity of Lists: " + driver.findElements(By.className("js-list")).size());
        //Adding new List
        driver.findElement(By.xpath("//div[@class='js-add-list list-wrapper mod-add is-idle']//span[@class='placeholder']")).click();
        waitUntilElementIsVisible((By.xpath("//input[@class='primary mod-list-add-button js-save-edit']")), 20);
        //Entering new List name
        driver.findElement(By.name("name")).sendKeys("AutoGeneratedList");
        waitUntilElementIsClickable(By.xpath("//input[@class='primary mod-list-add-button js-save-edit']"), 20);
        //Adding new List with entered name
        driver.findElement(By.xpath("//input[@class='primary mod-list-add-button js-save-edit']")).click();
        //Canceling other List adding
        waitUntilElementIsVisible((By.xpath("//a[@class='icon-lg icon-close dark-hover js-cancel-edit']")), 20);
        driver.findElement(By.xpath("//a[@class='icon-lg icon-close dark-hover js-cancel-edit']")).click();
        //Checking quantity of lists
        System.out.println("Quantity of Lists: " + driver.findElements(By.className("js-list")).size());
    }

    @Test
    public void trelloAddNewCard() {
        //Checking if any Lists exists on the board
        if ((driver.findElements(By.className("js-list")).size()) == 0) {
            //Adding new List
            driver.findElement(By.xpath("//div[@class='js-add-list list-wrapper mod-add is-idle']//span[@class='placeholder']")).click();
            waitUntilElementIsVisible((By.xpath("//input[@class='primary mod-list-add-button js-save-edit']")), 20);
            //Naming new List
            driver.findElement(By.name("name")).sendKeys("AutoGeneratedList");
            waitUntilElementIsClickable(By.xpath("//input[@class='primary mod-list-add-button js-save-edit']"), 20);
            //Adding newly named List
            driver.findElement(By.xpath("//input[@class='primary mod-list-add-button js-save-edit']")).click();
            //Canceling other List adding
            waitUntilElementIsVisible((By.xpath("//a[@class='icon-lg icon-close dark-hover js-cancel-edit']")), 20);
            driver.findElement(By.xpath("//a[@class='icon-lg icon-close dark-hover js-cancel-edit']")).click();
        }
        //Counting Cards
        System.out.println("Quantity of Cards: " + driver.findElements(By.className("js-card-name")).size());
        //Opening card composer
        driver.findElement(By.className("js-open-card-composer")).click();
        waitUntilElementIsVisible((By.className("js-add-card")), 20);
        //Entering card name
        driver.findElement(By.xpath("//textarea[@placeholder='Enter a title for this card…']")).sendKeys("AutoGeneratedCard");
        waitUntilElementIsClickable((By.className("primary confirm mod-compact js-add-card")), 10);
        //Adding card to the llist
        driver.findElement(By.xpath("//input[@class='primary confirm mod-compact js-add-card']")).click();
        //Counting Cards
        System.out.println("Quantity of Cards: " + driver.findElements(By.className("js-card-name")).size());
    }
    public String boardLocator(String boardTitle) {
        return "//div[@title = '" + boardTitle + "']/../..";
    }

}
